### PR TITLE
Updates to work with latest OnDemand

### PR DESCRIPTION
**Pull request by treydock**
Update to latest Slurm
Work with newer VirtualBox and Vagrant

### CODE REVIEW

**Comment by treydock** [comment]
@Oglopf I tested `vagrant-el8-with-slurm` works to spin up OnDemand 2.1 instance off RPMs.

**Comment by Oglopf** [comment]
Thanks @treydock for this. I keep hitting an error about using the `vagrant` gem though that seems to be deprecated in favor of `vagrant` on the OS (which I have). But when i issue the following:
```
vagrant plugin install vagrant-vbguest
export VAGRANT_EXPERIMENTAL="disks"
vagrant up head
```
I get an error about finding `vagrant` in my system gems. Should I be issuing a different sequence of commands to start things?

**Comment by Oglopf** [comment]
Well the vagrant issue just looks to be something on my end checking more. I'll have to figure out why this is going on (guessing RVM is involved). Nothings easy.

**Comment by Oglopf** [comment]
Hitting an error at the build that I'm unsure about:
```
$ vagrant up head
==> vagrant: You have requested to enabled the experimental flag with the following features:
==> vagrant: 
==> vagrant: Features:  disks
==> vagrant: 
==> vagrant: Please use with caution, as some of the features may not be fully
==> vagrant: functional yet.
Bringing machine 'head' up with 'virtualbox' provider...
==> head: Box 'rockylinux/8' could not be found. Attempting to find and install...
    head: Box Provider: virtualbox
    head: Box Version: >= 0
==> head: Loading metadata for box 'rockylinux/8'
    head: URL: https://vagrantcloud.com/rockylinux/8
==> head: Adding box 'rockylinux/8' (v7.0.0) for provider: virtualbox
    head: Downloading: https://vagrantcloud.com/rockylinux/boxes/8/versions/7.0.0/providers/virtualbox.box
Download redirected to host: dl.rockylinux.org
    head: Calculating and comparing box checksum...
==> head: Successfully added box 'rockylinux/8' (v7.0.0) for 'virtualbox'!
==> head: Importing base box 'rockylinux/8'...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "-n", "/home/trav/.vagrant.d/boxes/rockylinux-VAGRANTSLASH-8/7.0.0/virtualbox/box.ovf"]

Stderr: 0%...
Progress state: VBOX_E_OBJECT_NOT_FOUND
VBoxManage: error: Appliance read failed
VBoxManage: error: Failed to open OVF file '/home/trav/.vagrant.d/boxes/rockylinux-VAGRANTSLASH-8/7.0.0/virtualbox/box.ovf' (VERR_FILE_NOT_FOUND)
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component ApplianceWrap, interface IAppliance
VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg*)" at line 471 of file VBoxManageAppliance.cpp
```
The `box.ovf` is indeed not in the location, though it does have some files:
```
$ ls /home/trav/.vagrant.d/boxes/rockylinux-VAGRANTSLASH-8/7.0.0/virtualbox/
info.json  metadata.json  Rocky-8-Vagrant-Vbox-8.7-20221121.0.x86_64.vmdk  Vagrantfile
```
I've set `export` to start and tried to use the `virtualbox` suggestion of adding:
```
sudo mkdir /etc/vbox
sudo sh -c 'echo "* 10.0.0.0/8 192.168.0.0/16" > /etc/vbox/networks.conf'
```
But it still throws the same error at the `vagrant up head` command. Is this on my end, or should that `box.ovf` file be getting created somehow?

**Comment by gerald-byrket** [comment]
> My local machine I'm building on:
> 
> ```
> Distributor ID:	Ubuntu
> Description:	Ubuntu 22.04.1 LTS
> Release:	22.04
> Codename:	jammy
> ```
> 
> Unfortunately I'm hitting an error at the build that I'm unsure about:
> 
> ```
> $ vagrant up head
> ==> vagrant: You have requested to enabled the experimental flag with the following features:
> ==> vagrant: 
> ==> vagrant: Features:  disks
> ==> vagrant: 
> ==> vagrant: Please use with caution, as some of the features may not be fully
> ==> vagrant: functional yet.
> Bringing machine 'head' up with 'virtualbox' provider...
> ==> head: Box 'rockylinux/8' could not be found. Attempting to find and install...
>     head: Box Provider: virtualbox
>     head: Box Version: >= 0
> ==> head: Loading metadata for box 'rockylinux/8'
>     head: URL: https://vagrantcloud.com/rockylinux/8
> ==> head: Adding box 'rockylinux/8' (v7.0.0) for provider: virtualbox
>     head: Downloading: https://vagrantcloud.com/rockylinux/boxes/8/versions/7.0.0/providers/virtualbox.box
> Download redirected to host: dl.rockylinux.org
>     head: Calculating and comparing box checksum...
> ==> head: Successfully added box 'rockylinux/8' (v7.0.0) for 'virtualbox'!
> ==> head: Importing base box 'rockylinux/8'...
> There was an error while executing `VBoxManage`, a CLI used by Vagrant
> for controlling VirtualBox. The command and stderr is shown below.
> 
> Command: ["import", "-n", "/home/trav/.vagrant.d/boxes/rockylinux-VAGRANTSLASH-8/7.0.0/virtualbox/box.ovf"]
> 
> Stderr: 0%...
> Progress state: VBOX_E_OBJECT_NOT_FOUND
> VBoxManage: error: Appliance read failed
> VBoxManage: error: Failed to open OVF file '/home/trav/.vagrant.d/boxes/rockylinux-VAGRANTSLASH-8/7.0.0/virtualbox/box.ovf' (VERR_FILE_NOT_FOUND)
> VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component ApplianceWrap, interface IAppliance
> VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg*)" at line 471 of file VBoxManageAppliance.cpp
> ```
> 
> The `box.ovf` is indeed not in the location, though it does have some files:
> 
> ```
> $ ls /home/trav/.vagrant.d/boxes/rockylinux-VAGRANTSLASH-8/7.0.0/virtualbox/
> info.json  metadata.json  Rocky-8-Vagrant-Vbox-8.7-20221121.0.x86_64.vmdk  Vagrantfile
> ```
> 
> I've set `export` to start and tried to use the `virtualbox` suggestion of adding:
> 
> ```
> sudo mkdir /etc/vbox
> sudo sh -c 'echo "* 10.0.0.0/8 192.168.0.0/16" > /etc/vbox/networks.conf'
> ```
> 
> But it still throws the same error at the `vagrant up head` command. Is this on my end, or should that `box.ovf` file be getting created somehow?

This is the exact same problem I am having. i thought it was related to windows 11 since it worked fine when I ran vagrant up head on my work laptop which is windows 10 enterprise.

**Comment by treydock** [comment]
Both Vagrant and VirtualBox have native Windows support I believe, so maybe try that rather than doing it in WSL?  That is if you can't get the WSL approach to work.

**Comment by Oglopf** [comment]
I'm going to try and look around today to see if anyone else is hitting issues with that `VBoxManage` CLI command with virtualbox. I'm running on bare-metal ubuntu 22 when I hit the error.

**Comment by gerald-byrket** [comment]
> Both Vagrant and VirtualBox have native Windows support I believe, so maybe try that rather than doing it in WSL? That is if you can't get the WSL approach to work.

Sorry @treydock .  My post was misleading.  I'm not running it through wsl.  The error is the same, but the location of the missing file is in c:\Users\gbyrket\.vagrant.d\box\........

**Comment by gerald-byrket** [comment]
> > Both Vagrant and VirtualBox have native Windows support I believe, so maybe try that rather than doing it in WSL? That is if you can't get the WSL approach to work.
> 
> Sorry @treydock . My post was misleading. I'm not running it through wsl. The error is the same, but the location of the missing file is in c:\Users\gbyrket.vagrant.d\box........

image

**Comment by gerald-byrket** [comment]
If I copy the 2 folders in the screenshot from my work laptop to my personal pc, then everything works, with the exception of running out of virtual disk during the slurm install piece.

image

**Comment by treydock** [comment]
Ya I think Rocky just built a completely broken / corrupt image that lacks the OVF file which is essentially useless as OVF file is primary file for images.  I'll push a fix here in a bit once I run through the process locally using a different base image. I'm hoping this means I can also get rid of the wonky disk resizing since Rocky's old images were only 5GB root partition which is well below RedHat's recommendation of 20GB for EL8 installs.

**Comment by treydock** [comment]
@Oglopf @gerald-byrket Try now with latest changes I made. You can remove `VAGRANT_EXPERIMENTAL` environment variable as no longer needed.

**Comment by Oglopf** [comment]
Thanks Trey. Pulled the changes in and confirmed it is the `generic/rocky8` is there but I end with the same error unfortunately:
```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "-n", "/home/trav/.vagrant.d/boxes/rockylinux-VAGRANTSLASH-8/7.0.0/virtualbox/box.ovf"]

Stderr: 0%...
Progress state: VBOX_E_OBJECT_NOT_FOUND
VBoxManage: error: Appliance read failed
VBoxManage: error: Failed to open OVF file '/home/trav/.vagrant.d/boxes/rockylinux-VAGRANTSLASH-8/7.0.0/virtualbox/box.ovf' (VERR_FILE_NOT_FOUND)
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component ApplianceWrap, interface IAppliance
VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg*)" at line 471 of file VBoxManageAppliance.cpp
```
Is there anything I should do aside from issuing `vagrant up head` when trying to rebuild? Not sure if there's some cached layer or something trying to still use that old image.

**Comment by gerald-byrket** [comment]
> @Oglopf @gerald-byrket Try now with latest changes I made. You can remove `VAGRANT_EXPERIMENTAL` environment variable as no longer needed.

Hi @treydock .  Thanks for the progress made.  Here's the next error.

PS D:\workspace\ood-images\vagrant-el8-with-slurm> vagrant up head
Bringing machine 'head' up with 'virtualbox' provider...
==> head: Importing base box 'generic/rocky8'...
==> head: Matching MAC address for NAT networking...
==> head: Checking if box 'generic/rocky8' version '4.2.4' is up to date...
==> head: Setting the name of the VM: vagrant-el8-with-slurm_head_1670428931726_72952
==> head: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "ipconfig", "VirtualBox Host-Only Ethernet Adapter #7", "--ip", "10.0.0.1", "--netmask", "255.255.255.0"]

Stderr: VBoxManage.exe: error: The host network interface named 'VirtualBox Host-Only Ethernet Adapter #7' could not be found
VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component HostWrap, interface IHost, callee IUnknown
VBoxManage.exe: error: Context: "FindHostNetworkInterfaceByName(Bstr(pszName).raw(), hif.asOutParam())" at line 242 of file VBoxManageHostonly.cpp
PS D:\workspace\ood-images\vagrant-el8-with-slurm>

**Comment by treydock** [comment]
> Is there anything I should do aside from issuing `vagrant up head` when trying to rebuild? Not sure if there's some cached layer or something trying to still use that old image.

@Oglopf  You need to do `vagrant destroy` then re-run `vagrant up head`.  If you don't destroy the images from previous attempts, it will continue to use old image.

**Comment by treydock** [comment]
@gerald-byrket I have no clue, I don't use Windows.  I googled some of the errors you got and found a few links but not sure if useful.  https://forums.virtualbox.org/viewtopic.php?t=94277 and https://www.virtualbox.org/ticket/14545?cversion=0&cnum_hist=6 and https://github.com/hashicorp/vagrant/issues/4970

**Comment by Oglopf** [comment]
This is currently building correctly and working with: 
```
Ubuntu 22.04
virtualbox 6.1
vagrant 2.2.19`
```
But I want to wait to see if it works on Windows from  @gerald-byrket as well. Thanks for all the work on this Trey, I really appreciate it man.

**Comment by gerald-byrket** [comment]
> This is currently building correctly and working with:
> 
> ```
> Ubuntu 22.04
> virtualbox 6.1
> vagrant 2.2.19
> ```
> 
> But I want to wait to see if it works on Windows from @gerald-byrket as well. Thanks for all the work on this Trey, I really appreciate it man.



> @gerald-byrket I have no clue, I don't use Windows. I googled some of the errors you got and found a few links but not sure if useful. https://forums.virtualbox.org/viewtopic.php?t=94277 and https://www.virtualbox.org/ticket/14545?cversion=0&cnum_hist=6 and [hashicorp/vagrant#4970](https://github.com/hashicorp/vagrant/issues/4970)

Thanks @treydock .

The info from https://forums.virtualbox.org/viewtopic.php?t=94277  worked.

-gerald

**Comment by gerald-byrket** [comment]
Works great on 

VirtualBox 7.4
Windows 11 Professional
Vagrant 2.3.3

Thanks @treydock.  You rock!

**Review by gerald-byrket — APPROVED** [review]
All good from my respect.

**Pull request merged**
