### PR TITLE
Add podman

### PR DESCRIPTION
**Pull request by johrstrom**
Adds scripts to build and run Podman images.  Definitely builds a 'development' oriented image, with the one key aspect being (and why I built it) so that I can mount my actual files on my host to it and also be the same user inside the container. 

Docker may do something similar to podmans "userns=keep-id" which we could look into down the line in sort of unifying these images.  But I just wanted to commit this stuff, then we can start to look into merging the two.

### CODE REVIEW

**Comment by johrstrom** [comment]
In this PR I made the directory structure `container/podman` similarly, as we're discussing in #3 there'd be a `container/docker` folder, etc.

**Comment by johrstrom** [comment]
Anyone have any comments on this? Want see a demo? Again, this is the start of a `container/podman/xyz` directory structure which is the sort of biggest change. These are all new files, wherever they'll go.

**Comment by treydock** [comment]
If this setup is working for you I'd say merge it.

**Comment by johrstrom** [comment]
Thanks!

**Pull request merged**
