### PR TITLE
Directorize

### LINKED ISSUE #3: Combine with ood-images-full
There's a little bit of confusion with the ood-images-full repository and I've been working on images this morning, though in the buildah/podman stack. 

My proposal is this: to combine all logical "imaging" scripts/workflows/files into this repo.  

The initial directory structure would have at least these 4 sub directories.  I can start by committing my podman work in it's own directory, leaving everything else alone. 
```
vagrant/...
docker/...
packer/...
podman/...
```

This proposal ticket is then to agree on the idea, then note any pain points the migration may have, like some CI/CD workflow depending on file X to be at the top level directory (or even in the other repo)

@treydock @ericfranz @MorganRodgers FYC

### PR DESCRIPTION
**Pull request by johrstrom**
In an effort to close #3 this is the beginning of putting things into different directories. Note this only modifies the files in this repo, so it's only a shifting of the current files. It does not pull in files from other repos yet.

### CODE REVIEW

**Comment by treydock** [comment]
Both docker and Vagrant use `ood-setup.sh` which both require lives in same directory as the Dockerfile or Vagrantfile. I'm not sure if a symlink will work. Might be able to use relative path that is like `../ood-setup.sh`.

**Comment by johrstrom** [comment]
symlinks work for Dockerfile, are you worried about Windows? I do know symlinks sometimes misbehave on it. 

How about the common directory?  Maybe they both point to `../common/ood-setup.sh`?

**Comment by treydock** [comment]
I think a relative symlink to something in common directory is fine. Personally I could care less about Windows but maybe that's unfriendly to others who may use this repo. The docker directory at least is intended for us to provide others docker containers when we do releases, not really intended for interactive use by anyone else. If someone is going to do Vagrant then I'd say they should be using ood-images-full or those files once it's moved into here and that one I don't think would need anything from a common symlink.

**Comment by johrstrom** [comment]
Cool, I reset the symlinks, then just added them back. Again, I was able to build a container that correctly copied the symlinked file. I imagine Vagrant can follow the symlink? Though I can't test it myself.

**Comment by treydock** [comment]
I verified both Docker and Vagrant work with a symlink.

**Pull request merged**
